version: '3.7'

services:
  mysql:
    container_name: container_mysql
    image: mysql:latest
    volumes:
      - dbbase:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jwt_security
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - jwt_auth_network

volumes:
  dbbase:

networks:
  jwt_auth_network:

