spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
        "[hibernate.generate_statistics]": false
        "[hibernate.connection.provider_disables_autocommit]": true
